version: '3.8'

services:
  backend:
    image: 775727899931.dkr.ecr.ap-south-1.amazonaws.com/djjs-backend:latest
    container_name: djjs-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - djjs-net
    env_file:
      - .env
    # Alternative: Use environment variables directly (more secure for production)
    # environment:
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - PG_PORT=${PG_PORT}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - PORT=${PORT}
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #   - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    #   - AWS_REGION=${AWS_REGION}

networks:
  djjs-net:
    external: true

