
services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - eventreporting-net

volumes:
  db_data:

networks:
  eventreporting-net:
