name: Debug & Deploy (Docker â†’ ECR)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: djjs-backend
  CONTAINER_NAME: djjs-backend
  HOST_PORT: 8080
  CONTAINER_PORT: 8080
  ECR_REPOSITORY: 775727899931.dkr.ecr.ap-south-1.amazonaws.com/djjs-backend
  AWS_REGION: ap-south-1

jobs:
  debug_and_push:
    runs-on: [self-hosted, Linux, X64, label-3]
    outputs:
      image-tag: ${{ steps.set_tag.outputs.TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::775727899931:role/github-actions-ecr-role1
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ${AWS_REGION} | \
            docker login --username AWS --password-stdin ${ECR_REPOSITORY}

      - name: Build & push image
        id: set_tag
        run: |
          TAG=${GITHUB_SHA::7}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          IMAGE_URI="${ECR_REPOSITORY}:${TAG}"
          docker build -t ${IMAGE_NAME}:${TAG} -t ${IMAGE_NAME}:latest .
          docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_URI}
          docker push ${IMAGE_URI}
          docker tag ${IMAGE_NAME}:${TAG} ${ECR_REPOSITORY}:latest
          docker push ${ECR_REPOSITORY}:latest

  deploy:
    needs: debug_and_push
    runs-on: [self-hosted, Linux, X64, label-3]
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::775727899931:role/github-actions-ecr-role1
          aws-region: ap-south-1

      - name: Pull & run container
        run: |
          TAG=${{ needs.debug_and_push.outputs.image-tag }}
          IMAGE_URI="${ECR_REPOSITORY}:${TAG}"
          
          # Login
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
          
          # Pull latest image
          docker pull ${IMAGE_URI}
          
          # Remove old container if exists
          docker rm -f ${CONTAINER_NAME} || true
          
          # RUN WITH DATABASE ENV VARIABLES
          # --add-host=host.docker.internal:host-gateway allows container to talk to Host OS
          docker run -d --name ${CONTAINER_NAME} \
            --add-host=host.docker.internal:host-gateway \
            -p ${HOST_PORT}:${CONTAINER_PORT} \
            -e POSTGRES_HOST=host.docker.internal \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_USER="${{ secrets.DB_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e POSTGRES_DB="${{ secrets.DB_NAME }}" \
            --restart always \
            ${IMAGE_URI}
